name: Vérification du respect des spécifications

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Installation des dépendances
      run: pip install -r requirements.txt
    - name: Vérification du schéma operation-amenagement et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema schema/operation-amenagement/schema.json
        frictionless validate --schema schema/operation-amenagement/schema.json schema/operation-amenagement/exemple-valide.csv
    - name: Vérification du schéma secteur et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema schema/secteur/schema.json
        frictionless validate --schema schema/secteur/schema.json schema/secteur/exemple-valide.csv
    - name: Vérification du schéma programme et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema schema/programme/schema.json
        frictionless validate --schema schema/programme/schema.json schema/programme/exemple-valide.csv
    - name: Vérification du datapackage
      run: |
        frictionless validate schema/datapackage.json
